# Generated by Django 5.1.6 on 2025-03-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('driver_id', models.IntegerField()),
                ('description', models.TextField()),
                ('origin', models.TextField()),
                ('destination', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'shipments',
            },
        ),
    ]
