# Generated by Django 5.1.6 on 2025-03-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('company', 'Company'), ('driver', 'Driver'), ('admin', 'Admin')], default='driver', max_length=10),
        ),
    ]
